language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode7.2b3
    - os: osx
      osx_image: xcode7.2b1
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: xcode7
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: beta-xcode6.3
    - os: osx
      osx_image: beta-xcode6.2g
    - os: osx
before_install:
  - gem install github-markdown
before_script:
  - make docs
xcode_workspace: Hammerspoon.xcworkspace
xcode_scheme: Release
after_script:
  - make build/html
notifications:
  irc:
    channels:
      - "irc.freenode.net#hammerspoon"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
